// Main Input Endpoints
export type PlayerContractType = {
    'id': number,
    'PlayerName': string,
    'Pos': NHLPositions,
    'Years': 1 | 2 | 3,
    'AAV': number,
    'SigningTeam': number,
    'CurrentTeam': number,
    'SigningDate': Date,
    'StartDate': Date,
    'SignType': 'Draft' | 'RFA' | 'UFA',
    'ExpiryType': 'RFA' | 'UFA' | 'Buyout',
    'EndDate': Date,
    'CapHit': number,
    'CapHitExpiry': Date,
    'YearsRemaining': number,
}
export type ScheduleMatchupType = {
    'id': number,
    'Season':Seasons,
    'WeekNum':number,
    'StartDate':Date,
    'EndDate':Date,
    'GameDays': number,
    'GameType': WeekTypes,
    'MatchupNum': number,
    'HomeRank': number | null,
    'HomeTeam': number | null,
    'HomeScore': number | null,
    'HomeWL': 'W' | 'L' | 'T' | null,
    'AwayRank': number | null,
    'AwayTeam': number | null,
    'AwayScore': number | null,
    'AwayWL': 'W' | 'L' | 'T' | null,
    'FirstStar': number | null,
    'SecondStar': number | null,
    'ThirdStar': number | null,
    'MatchupRtg': number | null,
}
export type ScheduleWeekType = {
    'id': number,
    'Season': number,
    'WeekNum': number,
    'StartDate': Date,
    'EndDate': Date,
    'GameDays': number,
    'WeekType': 'RS' | 'PO',
}
export type TeamInfoType = {
    'id': number,
    'TeamName': string,
    'OwnerID': number,
    'LogoURL': string,
    'Conference': 'SV' | 'HH',
    '2015': number,
    '2016': number,
    '2017': number,
    '2018': number,
    '2019': number,
    '2020': number,
    '2021': number,
    '2022': number,
    '2023': number,
    '2024': number,
    '2025': number,
    '2026': number,
}
export type OwnerInfoType = {
    'id': number,
    'FirstName': string,
    'LastName': string,
    'Nickname': string,
    'Email': string,
}


// Player Data Endpoints
type PlayerDaysInfoType = {
    'id': number,
    'Season': Seasons,
    'WeekNum': number,
    'WeekType': WeekTypes,
    'Date': Date,
    'PlayerName': string,
    'nhlPos': NHLPositions,
    'nhlTeam': string | null,
    'Injury': InjuryDesignations,
    'PosGroup': PositionGroups,
    'DailyPos': GSHLPositions,
    'Opp': string | null,
    'Score': string | null,
    'YahooRk': number | null,
    'gshlTeam': number,
    'GP': number | null,
    'PPD': number | null,
    'MG': number | null,
    'GS': number | null,
    'Rating': number,
    'FullPos': GSHLPositions,
    'BestPos': GSHLPositions,
    'MS': number | null,
    'BS': number | null,
}
export type PlayerDaysSkaterType = PlayerDaysInfoType & {
    'G': number | null,
    'A': number | null,
    'P': number | null,
    'PPP': number | null,
    'SOG': number | null,
    'HIT': number | null,
    'BLK': number | null,
}
export type PlayerDaysGoalieType = PlayerDaysInfoType & {
    'W': number | null,
    'GA': number | null,
    'GAA': number | null,
    'SV': number | null,
    'SA': number | null,
    'SVP': number | null,
    'TOI': number | null,
}
export type PlayerWeeksType = {
    'id': number,
    'Season': Seasons,
    'WeekNum': number,
    'WeekType': WeekTypes,
    'PlayerName': string,
    'nhlPos': NHLPositions,
    'PosGroup': PositionGroups,
    'nhlTeam': string | null,
    'gshlTeam': string,
    'RosterDays': number,
    'GP': number | null,
    'PPD': number | null,
    'MG': number | null,
    'GS': number | null,
    'G': number | null,
    'A': number | null,
    'P': number | null,
    'PPP': number | null,
    'SOG': number | null,
    'HIT': number | null,
    'BLK': number | null,
    'W': number | null,
    'GA': number | null,
    'GAA': number | null,
    'SV': number | null,
    'SA': number | null,
    'SVP': number | null,
    'TOI': number | null,
    'MS': number,
    'BS': number,
    'Rating': number,
}
export type PlayerSplitsType = {
    'id': number,
    'Season': Seasons,
    'WeekType': WeekTypes,
    'PlayerName': string,
    'nhlPos': NHLPositions,
    'PosGroup': PositionGroups,
    'nhlTeam': string | null,
    'gshlTeam': number,
    'RosterDays': number,
    'GP': number,
    'PPD': number,
    'MG': number,
    'GS': number,
    'G': number | null,
    'A': number | null,
    'P': number | null,
    'PPP': number | null,
    'SOG': number | null,
    'HIT': number | null,
    'BLK': number | null,
    'W': number | null,
    'GA': number | null,
    'GAA': number | null,
    'SV': number | null,
    'SA': number | null,
    'SVP': number | null,
    'TOI': number | null,
    'MS': number,
    'BS': number,
    'Rating': number,
}
export type PlayerTotalsType = {
    'id': number,
    'Season': Seasons,
    'WeekType': WeekTypes,
    'PlayerName': string,
    'nhlPos': NHLPositions,
    'PosGroup': PositionGroups,
    'nhlTeam': string[] | null,
    'gshlTeam': number[],
    'RosterDays': number,
    'GP': number | null,
    'PPD': number | null,
    'MG': number | null,
    'GS': number | null,
    'G': number | null,
    'A': number | null,
    'P': number | null,
    'PPP': number | null,
    'SOG': number | null,
    'HIT': number | null,
    'BLK': number | null,
    'W': number | null,
    'GA': number | null,
    'GAA': number | null,
    'SV': number | null,
    'SA': number | null,
    'SVP': number | null,
    'TOI': number | null,
    'MS': number,
    'BS': number,
    'Rating': number,
}
export type PlayerNHLType = {
    'id': number,
    'Season': Seasons,
    'PlayerName': string,
    'PosGroup': PositionGroups,
    'nhlTeam': string,
    'Age': number,
    'GP': number,
    'GS': number | null,
    'G': number | null,
    'A': number | null,
    'P': number | null,
    'PM': number | null,
    'PIM': number | null,
    'PPP': number | null,
    'SOG': number | null,
    'HIT': number | null,
    'BLK': number | null,
    'W': number | null,
    'L': number | null,
    'OTL': number | null,
    'GA': number | null,
    'GAA': number | null,
    'SV': number | null,
    'SA': number | null,
    'SVP': number | null,
    'TOI': number | null,
    'Rating': number,
}
export type PlayerSalariesType = {
    'Season': Seasons,
    'id': number,
    'PlayerName': string,
    'gshlTeam': number | null,
    'PosGroup': PositionGroups,
    'Age': number,
    'Rating': number,
    'ProjectedSalary': number,
    'CurrentSalary': number | null,
    'EarlySalary': number | null,
    'LateSalary': number | null,
    'Status': 'Contract' | 'Draft',
    'Savings': number | null,
    '2015': number | null,
    '2016': number | null,
    '2017': number | null,
    '2018': number | null,
    '2019': number | null,
    '2020': number | null,
    '2021': number | null,
    '2022': number | null,
    '2023': number | null,
    '2024': number | null,
    '2025': number | null,
    '2026': number | null,
}
export type PlayerCurrentRosterType = {
    'id': number,
    'Season': Seasons,
    'PlayerName': string,
    'nhlPos': NHLPositions,
    'posGroup': PositionGroups,   // Must be set in fetch function
    'nhlTeam': string,
    'gshlTeam': number,
    'Rating': number,
    'Rank': number,
    'ContractEligible': Boolean,
    'LineupPos': GSHLPositions,
}
export type PlayerDraftHistoryType = {
    'Season': number,
    'Rd': number,
    'Pick':number,
    'PlayerName':string,
    'gshlTeam':number,
    'SplitRtg':number,
    'TotalRtg':number,
    'SplitRatio':number,
    'CalderRtg':number,
    'PickRtg':number,
}
export type PlayerAllStarsType = PlayerTotalsType & {
    'LineupPos': string,
}


// Team Data Endpoints
export type TeamDaysType = {
    'id': number,
    'Season': Seasons,
    'WeekNum': number,
    'WeekType': WeekTypes,
    'Date': Date,
    'gshlTeam': number,
    'GP': number,
    'GPg': number,
    'PPD': number,
    'MG': number,
    'MGg': number,
    'GS': number,
    'GSg': number,
    'G': number,
    'A': number,
    'P': number,
    'PPP': number,
    'SOG': number,
    'HIT': number,
    'BLK': number,
    'W': number,
    'GA': number,
    'GAA': number | null,
    'SV': number,
    'SA': number,
    'SVP': number | null,
    'TOI': number,
    'MS': number,
    'BS': number,
    'Rating': number,
}
export type TeamWeeksType = {
    'id': number,
    'Season': Seasons,
    'WeekNum': number,
    'WeekType': WeekTypes,
    'gshlTeam': number,
    'GP': number,
    'GPg': number,
    'PPD': number,
    'MG': number,
    'MGg': number,
    'GS': number,
    'GSg': number,
    'G': number,
    'A': number,
    'P': number,
    'PPP': number,
    'SOG': number,
    'HIT': number,
    'BLK': number,
    'W': number,
    'GA': number,
    'GAA': number,
    'SV': number,
    'SA': number,
    'SVP': number,
    'TOI': number,
    'MS': number,
    'BS': number,
    'Rating': number,
    'YTDRtg': number,
    'PwrRtg': number,
    'PwrRk': number,
}
export type TeamTotalsType = {
    'id': number,
    'Season': Seasons,
    'WeekType': WeekTypes,
    'gshlTeam': number,
    'GP': number,
    'GPg': number,
    'PPD': number,
    'MG': number,
    'MGg': number,
    'GS': number,
    'GSg': number,
    'G': number,
    'A': number,
    'P': number,
    'PPP': number,
    'SOG': number,
    'HIT': number,
    'BLK': number,
    'W': number,
    'GA': number,
    'GAA': number,
    'SV': number,
    'SA': number,
    'SVP': number,
    'TOI': number,
    'MS': number,
    'BS': number,
    'Rating': number,
    'Players': number | null,
    'Norris': number | null,
    'Vezina': number | null,
    'Calder': number | null,
    'JackAdams': number | null,
    'GMOY': number | null,
}
export type TeamStandingsType = {
    'Season':number,
    'gshlTeam':number,
    'TeamName': string,
    'Owner':number,
    'LogoURL':string,
    'Conf': 'SV'|'HH',
    'W':number,
    'HW':number,
    'HL':number,
    'L':number,
    'PTS':number,
    'CF':number,
    'CA':number,
    'Diff':number,
    'CCW':number,
    'CCHW':number,
    'CCHL':number,
    'CCL':number,
    'CCPTS':number,
    'CCCF':number,
    'CCCA':number,
    'CCDiff':number,
    'POW':number,
    'POHW':number,
    'POHL':number,
    'POL':number,
    'POPTS':number,
    'POCF':number,
    'POCA':number,
    'PODiff':number,
    'LTW':number,
    'LTHW':number,
    'LTHL':number,
    'LTL':number,
    'LTPTS':number,
    'LTCF':number,
    'LTCA':number,
    'LTDiff':number,
    'Stk':string,
    'Rtg':number,
    'Rk':number,
    'PrevRtg':number,
    'PrevRk':number,
    'RtgCh':number,
    'RkCh':number,
    'POFinish':string,
    'POPer':number|null,
    'OvrRk':number,
    'WCRk':number|null,
    'LTRk':number|null,
    'CCRk':number,
    'DraftPtsAdj':number|null,
}
export type TeamAwardWinnersType = TeamTotalsType & {
    'Award': string
}
export type TeamAwardNomineesType = TeamAwardWinnersType & {
    'Prob': string,
}
export type TeamDraftPickType ={
    'Season':Seasons,
    'Rd':number,
    'Pick':number,
    'gshlTeam':number,
    'OriginalTeam':number,
}
export type TeamDraftOrderType = TeamStandingsType & {
    'Slot': number,
}


// Utility Types
export type SeasonInfoDataType = {
    'Season': Seasons,
    'CurrentNHLGamesPlayed': number,
    'SeasonStartDate': Date,
    'SeasonEndDate': Date,
    'SeasonDays': number,
    'SeasonLength': number,
    'PlayoffStartDate': Date,
    'PlayoffEndDate': Date,
    'PlayoffDays': number,
    'EarlySigningStartDate': Date,
    'EarlySigningEndDate': Date,
    'LateSigningStartDate': Date,
    'LateSigningEndDate': Date,
    'Positions': [string[], number[]],
    'Categories': string[],
    'PlayerData': string,
    'TeamData': string,
}
export type QueryKeyType = [Seasons, 'PlayerData' | 'TeamData' | 'MainInput', string]
export type LockerRoomPlayerStatPropsType = { 'teamInfo': TeamInfoType | undefined, 'season': Seasons, 'playerSeasonData': PlayerSplitsType[], 'currentRosterData': PlayerRosterType[],'teamContracts':PlayerContractType[] }
export type LockerRoomTeamStatPropsType = { 'teamInfo': TeamInfoType | undefined, 'season': Seasons, 'teamWeeksData': TeamWeeksType[], 'teamSeasonsData': TeamTotalsType[],'teamContracts':PlayerContractType[] }
export type Seasons = 2015 | 2016 | 2017 | 2018 | 2019 | 2020 | 2021 | 2022 | 2023
type WeekTypes = 'RS' | 'NC' | 'CC' | 'PO' | 'QF' | 'SF' | 'F' | 'LT'
type NHLPositions = 'C' | 'C,LW' | 'C,RW' | 'C,LW,RW' | 'LW' | 'LW,RW' | 'RW' | 'D' | 'G'
type GSHLPositions = 'C' | 'LW' | 'RW' | 'D' | 'G' | 'Util' | 'BN' | 'IR+' | 'IR'
type InjuryDesignations = 'DTD' | 'O' | 'IR' | 'IR-LT' | 'IR-NR' | 'COVID-19' | 'SUSP' | 'NA' | null
type PositionGroups = 'F' | 'D' | 'G'
//